// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

using Eco.Gameplay.Items;
using Eco.Gameplay.Players;
using Village.Eco.Mods.Cooking;

namespace Eco.Mods.TechTree
{
    public partial class MeatyStewItem
    {
        public override string OnUsed(Player player, ItemStack itemStack)
        {
            var message = base.OnUsed(player, itemStack);

            if (message != "")
            {
                var result = player.User.Inventory.TryAddItemNonUnique(typeof(WoodenBowlItem));
                if (result.Success) player.User.InfoBoxLocStr("Chanceux ! Tu as récupéré un bol.");
            }
            return message;
        }
        
        public string Consume(Player player) => OnUsed(player, player.User.Inventory.Toolbar.SelectedStack);
    }
}